= XOR
:hardbreaks:

XOR is a tool that allows users to perform CRUDQ (Create, Read, Update, Delete, Query) operations over a Data Model using a uniform interface over a meta model of the Data model. It has mechanisms to allow a user to control how some of these operations are implemented. This allows it to address performance concerns related to persistence in a J2EE environment.

In a typical J2EE environment, a development team has to interact with the following 3 data models:

1. *UI model* - Schema section in swagger for REST APIs
2. *Java model* - Business logic classes modeled in an ORM 
3. *Database model* - Tables and foreign keys in an RDBMS

Support comes out of the box for Swagger, JPA and JDBC representations for these models. It is possible for other models to be plugged into this architecture.

= Data patterns
A couple of data patterns rise to the top in terms of performance related to persistence.

== Data retrieval
When a UI needs to retrieve data to populate its model it has to go through 2 transformations
  
       +------------+     1     +--------------+    2     +---------------+
       |  UI Model  |---------->|  JPA model   |--------->|   JDBC model  |      
       +------------+           +--------------+          +---------------+

Transformation #1 is usually straightforward, as it is a mapping from a Java object to a JSON object and 
can be done in-memory.
Transformation #2 is where most of the performance issues occur. This happens because the ORM layer tries
to hide most of the complexity between the Object Oriented to the Relational model mapping.
Depending on how this mapping is done and how complex the business model is, some queries can perform
very badly.
XOR addresses this issue by allowing the web developer to express the data retrieval request directly
against the RDBMS using the UI model, thereby bypassing transformation #2.

== Data generation
There are many times when we need to generate a large amount of data in a reasonable time:

* Troubleshoot a performance issue when access to the customer's data is not permitted
* Create a large data set for performance testing and the model is rapidly evolving

As shown in the diagram above, transformation #2 puts a large overhead when populating the database.
XOR allows the user to directly access the JDBC model and generate data as needed. 
It supports the concept of generators for each field. 
A generator can specify how the data needs to be populated for e.g., 

* Data for simple data types 
* Data needed to model association relationships 
* Data needed to model inheritance relationships.

= Uniform type interface

The access to the above 3 models is exposed through XOR using a common type system. This type system models the data as JSON objects.
For example, in the UI model the XOR tool is initialized with the swagger schema and for the JDBC model, it is initialized by reading the tables and foreign keys using the appropriate database dialect.

This architecture allows XOR to also be used as a data migration tool between incompatible models, as long as the necessary data conversion is performed on the JSON object to match the type appropriate for each model.

= Configuration

Depending on the use case configuration requirements to use XOR varies.
Before we address the configuration requirements we need to understand the following concepts

== Model classification

A data model can be one of 2 forms depending on how it is created

1. *Prescribed* - User specifies the model. For e.g., swagger or JSON schema document
2. *Derived* - The model is derived from another model. For e.g., JPA metadata or RDBMS catalog

XOR works with models of any of the above 2 forms transparently since it uses a uniform type interface. 
But the CRUDQ operations on a Prescribed model might be limited, depending on the configuration.

== Architecture

The configuration is directly tied to the architecture of XOR. 
XOR is a data transformation tool, taking data from one model representation and transforming it to data in another model representation.
Below is the anatomy of the transformation process



= Takeaway

As you can see in both the above data patterns, performance concerns are addressed by reducing the number of transformations that data has to go through. 
XOR allows the user to work with the data model closest to the task at hand.
We improve the performance for the Data retrieval pattern by working with the UI model and for the Data generation pattern by working with the JDBC model.

== License
This project is licensed under https://apache.org/licenses/LICENSE-2.0[Apache 2.0 license].
