= XOR
:hardbreaks:

XOR is a tool designed to address performance concerns related to persistence in a J2EE environment.
It is powered using a meta model to make decisions.

In a typical J2EE environment, a development team has to interact with the following 3 data models:

1. *UI model* - Schema section in swagger for REST APIs
2. *Java model* - Business logic classes modelled in an ORM 
3. *Database model* - Tables and foreign keys in an RDBMS

Support comes out of the box for Swagger, JPA and JDBC representations for these models. It is possible for other models to be plugged into this architecture.

= Data patterns
A couple of data patterns rise to the top in terms of performance related to persistence.

== Data retrieval
When a UI needs to retrieve data to populate its model it has to go through 2 transformations
  
       +------------+     1     +--------------+    2     +---------------+
       |  UI Model  |---------->|  JPA model   |--------->|   JDBC model  |      
       +------------+           +--------------+          +---------------+

Transformation #1 is usually straightforward, as it is a mapping from a Java object to a JSON object and 
can be done in-memory.
Transformation #2 is where most of the performance issues occur. This happens because the ORM layer tries
to hide most of the complexity between the Object Oriented to the Relational model mapping.
Depending on how this mapping is done and how complex the business model is, some queries can perform
very badly.
XOR addresses this issue by allowing the web developer to express the data retrieval request directly
against the RDBMS using the UI model, thereby bypassing transformation #2.

== Data generation
There are many times when we need to generate a large amount of data in a reasonable time:

* Troubleshoot a performance issue when access to the customer's data is not permitted
* Create a large data set for performance testing and the model is rapidly evolving

As shown in the diagram above, transformation #2 puts a large overhead when populating the database.
XOR allows the user to directly access the JDBC model and generate data as needed. 
It supports the concept of generators for each field. 
A generator can specify how the data needs to be populated for e.g., 

* Data for simple data types 
* Data needed to model association relationships 
* Data needed to model inheritance relationships.

= Takeaway

As you can see in both the above data patterns, performance concerns are addressed by reducing the number of transformations that data has to go through. 
XOR allows the user to work with the data model closest to the task at hand.
We improve the performance for the Data retrieval pattern by working with the UI model and for the Data generation pattern by working with the JDBC model.

== License
This project is licensed under https://apache.org/licenses/LICENSE-2.0[Apache 2.0 license].
