/**
 * XOR, empowering Model Driven Architecture in J2EE applications
 *
 * Copyright (c) 2012, Dilip Dalton
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations 
 * under the License.
 */

package tools.xor.view;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.regex.MatchResult;

import javax.mail.Store;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

import tools.xor.AggregateAction;
import tools.xor.EntityType;
import tools.xor.Type;
import tools.xor.service.DataAccessService;
import tools.xor.util.DFAtoRE;
import tools.xor.util.Edge;
import tools.xor.util.State;
import tools.xor.util.Vertex;
import tools.xor.util.graph.StateGraph;
import tools.xor.view.QueryView.ViewKey;

/*
 * If no view/qualifier is specified then we return all the properties and children of the aggregate
 * 
 * We are not dealing with an XML document, so there is no inherent context to work with, i.e, one cannot navigate to a parent from the root etc..
 * Also XML document is a tree and not a graph and we have to deal with references, so we need additional constructs to represent that.
 * 
 * The view also allows qualifiers with special meaning.:
 *   <path><empty>    - If the path represents an entity, then include only initialized properties
 *   <path>.<path>*   - recursive path
 *   <path>.(<path>)* - recursive path with multiple elements in a recursive chain
 *   
 *   List the structure and copy the desired subset into the view.
 *   
 *   
 *   
 *   DEPRECATED below
 *   <path>|          - Single association reference
 *   <path>^          - Collection references
 *   <path>//         - All descendants
 *   <path1>//<path2> - Any property anchored with <path1> that ends with <path2>
 *   !<path>          - Exclude the particular path pattern from the view. The negative rules have greater precedence.
 *   <path>.∞         - All the properties including descendant objects of the aggregate and other associations
 *                      This can potentially load the complete DB!
 *                
 * Precedence rules:
 * 1. ! - Highest precedence
 * 2. <path> 
 * 3. <path><qualifier>
 * 4. <path>//<path><qualifier>
 * 5. //<path><qualifier>
 *                 
 * Examples: 
 *   <path>//      - All descendants of the aggregate with the leaf children having only the initialized fields
 *   <path>//@|    - All descendants of the aggregate with the leaf children having all attributes and single association initialized
 *   <path>//^     - All descendants including collection references and no @ or |
 *   
 * @author Dilip Dalton
 *
 */

@XmlRootElement(name="AggregateView")
public class AggregateView implements Comparable<AggregateView>, Vertex {
	private static final Logger logger = LogManager.getLogger(new Exception().getStackTrace()[0].getClassName());
	
	public static final String VIEW_REFERENCE_START = "[";
	public static final String VIEW_REFERENCE_NAME_REGEX = "^.*\\[\\s*(\\w+)\\s*\\].*";
	public static final String VIEW_REFERENCE_MULTIPLE_REGEX = "^(.*)(\\[\\s*(\\w+)\\s*\\]).*(\\[\\s*\\w+\\s*\\].*)";
	public static final String VIEW_REFERENCE_PREFIX_REGEX = "^(.*)\\[\\s*\\w+\\s*\\].*";
	
	public static final String BASE = "BASE_";
	public static final String RECURSIVE = "RECURSIVE_";
	public static final String DOMAIN = "DOMAIN:";

	// The user can specify child branches if necessary directly. 
	// NOTE: If one or more child branch are specified, then only the child branches are executed.
	protected String            name;
	protected List<String>      attributeList;
	protected String            typeName; // represents the root entity type
	
	// Each filter item should be independent of one another
	protected List<Filter>      filter;      
	
	// OQL query generated by the system. May not be an optimized version.
	protected OQLQuery          systemOQLQuery;
	
	// OQL query crafted by the user, useful for providing an optimized OQL version.
	protected OQLQuery          userOQLQuery;
	
	// It should refer to the full attribute name
	// SQL - the column names should be PROP1, PROP2 etc...
	protected NativeQuery       nativeQuery; 
	
	protected List<StoredProcedure>   storedProcedure;
	
	//  validation should be done by the PersistenceOrchestrator
	// If the children are specified, it is not necessary to split it automatically
	// and we will trust the user has done a better split
	// NOTE: Only one level of child Content views are permitted. Nesting is not allowed.
	protected List<AggregateView> children;    
	
	// The parameters specified in the filter or in the native query
	protected List<Parameter>   parameter;  
	protected Join              join;
	
	protected int               version; // The version from which this view is effective
	
	@XmlTransient
	private boolean expanded;

	@XmlTransient
	private boolean union;
	
	@XmlTransient
	private Set<String> exactAttributes; // These do not have the recursive operand (*) and
	                                     // and exact match can be performed
	
	@XmlTransient
	private DataAccessService DAS; // The data access service with which this view is associated
	
	@XmlTransient
	private Map<ViewKey, QueryView>  viewCache = new ConcurrentHashMap<ViewKey, QueryView>();	

	// A view can be valid for multiple entity types, especially if the view refers
	// to the attributes in a base class. Then in this case, the view can be 
	// used by all the subtypes of that base class.
	@XmlTransient
	private Map<String, StateGraph<State, Edge<State>>> stateGraph =  new ConcurrentHashMap<String, StateGraph<State, Edge<State>>>();

	public AggregateView(QueryView queryView) {
		initQuery(queryView);
	}
	
	public AggregateView(Type type, String viewName) {
		this(viewName);
		this.typeName = type.getInstanceClass().getName();
	}	
	
	public AggregateView(String viewName) {
		setName(viewName);
	}		

	/**
	 * No-args constructor required for Unmarshalling purpose and also internally by the framework. 
	 * Don't use this directly.
	 */
	public AggregateView() {
	}
	
	public void initQuery(QueryView queryView) {
		this.name = queryView.getName();
		this.typeName = queryView.getAggregateType().getInstanceClass().getName();
		
		// We create the OQLQuery object and populate it with information from the query view
		// such as ColumnMeta information
		// The query builder should have populated the OQLQuery object
	}

	public boolean isExpanded() {
		return expanded;
	}

	public void setExpanded(boolean expanded) {
		this.expanded = expanded;
	}
	
	public boolean isUnion() {
		return union;
	}

	public void setUnion(boolean union) {
		this.union = union;
	}
	
	public int getVersion() {
		return version;
	}

	public void setVersion(int version) {
		this.version = version;
	}	

	public Join getJoin() {
		return join;
	}

	public void setJoin(Join join) {
		this.join = join;
	}

	public List<Parameter> getParameter() {
		return parameter;
	}

	public void setParameter(List<Parameter> parameter) {
		this.parameter = parameter;
	}

	public List<AggregateView> getChildren() {
		return children;
	}

	public void setChildren(List<AggregateView> children) {
		this.children = children;
	}

	public List<Filter> getFilter() {
		return filter;
	}

	public void setFilter(List<Filter> filters) {
		this.filter = filters;
	}	

	public OQLQuery getSystemOQLQuery() {
		return systemOQLQuery;
	}

	public void setSystemOQLQuery(OQLQuery systemOQLQuery) {
		this.systemOQLQuery = systemOQLQuery;
	}

	public OQLQuery getUserOQLQuery() {
		return userOQLQuery;
	}

	public void setUserOQLQuery(OQLQuery userOQLQuery) {
		this.userOQLQuery = userOQLQuery;
	}

	public NativeQuery getNativeQuery() {
		return nativeQuery;
	}

	public void setNativeQuery(NativeQuery nativeQuery) {
		this.nativeQuery = nativeQuery;
	}

	public StoredProcedure getStoredProcedure(final AggregateAction action) {
		StoredProcedure result = null;

		if(getStoredProcedure() != null) {
			for (StoredProcedure sp : getStoredProcedure()) {
				if (sp.getAction() == action) {
					result = sp.copy();
					break;
				}
			}
		}

		return result;
	}

	public List<StoredProcedure> getStoredProcedure() {
		return storedProcedure;
	}

	public void setStoredProcedure(List<StoredProcedure> storedProcedure) {
		this.storedProcedure = storedProcedure;
	}

	@XmlTransient
	public DataAccessService getDAS() {
		return DAS;
	}

	public void setDAS(DataAccessService dAS) {
		DAS = dAS;
		
		if(children != null) {
			for(AggregateView child: children) {
				child.setDAS(dAS);
			}
		}		
	}	

	public List<String> getAttributeList() {
		if(attributeList == null && children != null) { // UNION functionality
			setUnion(true);
			attributeList = new ArrayList<String>();
			for(AggregateView child: children)
				attributeList.addAll(child.getAttributeList());
		}
		return attributeList;
	}

	public void setAttributeList(List<String> attributeList) {
		this.attributeList = attributeList;
	}

	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Override
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean hasNativeQuery() {
		boolean result = true;

		if(children == null)
			result = nativeQuery != null;
		else {
			boolean found = false;
			for(AggregateView child: children) {
				if(!child.hasNativeQuery())
					result = false;
				else
					found = true;
			}
			if(found && !result)
				logger.warn("If a native query is specified, it needs to be specified on all branches or it will not be used");
		}

		return result;
	}
	
	private QueryView getQueryView(ViewKey viewKey) {
		if(viewCache.containsKey(viewKey))
			return viewCache.get(viewKey);
		
		QueryView result = new QueryView(viewKey, this);
		viewCache.put(viewKey, result);

		return result;
	}

	public QueryView getEntityView(Type type, boolean narrow) {
		if(children != null) {
			for(AggregateView child: children)
				if(child.children != null && child.children.size() > 0)
					throw new IllegalArgumentException("A content view cannot have more than one level of child content views");
		}
		
		QueryView result = getQueryView(new ViewKey(type, name, narrow));

		return result;
	}

	public Set<String> getParameterNames() {
		Set<String> result = new HashSet<String>();

		if(parameter != null)
			for(Parameter param: parameter)
				result.add(param.name);

		return result;
	}
	
	public AggregateView copy() {
		AggregateView result = new AggregateView();

		result.setName(name);
		if(attributeList != null) {
			result.setAttributeList(new ArrayList<String>(attributeList));
		}

		if(filter != null) {
			List<Filter> filterCopy = new ArrayList<Filter>();
			for(Filter f: filter) {
				filterCopy.add(new Filter(f.expression, f.position));
			}
			result.setFilter(filterCopy);
		}

		if(nativeQuery != null) {
			result.setNativeQuery(nativeQuery.copy());
		}

		if(children != null) {
			List<AggregateView> childrenCopy = new ArrayList<AggregateView>();
			for(AggregateView c: children) {
				childrenCopy.add(c.copy());
			}
			result.setChildren(childrenCopy);
		}

		// TODO: can this be made immutable
		if(parameter != null) {
			result.setParameter(new ArrayList<Parameter>(parameter));
		}

		result.setJoin(join);
		result.setUnion(union);

		if(exactAttributes != null) {
			result.exactAttributes = new HashSet<String>(exactAttributes);
		}
		
		if(stateGraph != null) {
			for(Map.Entry<String, StateGraph<State, Edge<State>>> entry: stateGraph.entrySet()) {
				result.stateGraph.put(entry.getKey(), entry.getValue().copy());
			}
		}
		
		result.setDAS(getDAS());

		return result;
	}
	
	public Set<String> getViewReferences() {
		Set<String> result = new HashSet<String>();
		
		for(String attribute: getAttributeList()) {
			String viewName = getViewReference(attribute);
			if(viewName != null)
				result.add(viewName);
		}
		
		return result;
	}
	
	private String getViewReference(String attribute) {
		if(attribute.matches(VIEW_REFERENCE_NAME_REGEX)) {
			Scanner s = new Scanner(attribute);
			try {
				s.findInLine(VIEW_REFERENCE_NAME_REGEX);
				MatchResult result = s.match();
				if(result.groupCount() == 1)
					return result.group(1);
			} finally {
				s.close();
			}
		}

		return null;
	}
	
	public boolean hasViewReference() {
		 
		for(String attribute: getAttributeList()) {
			if(getViewReference(attribute) != null)
				return true;
		}
		
		return false;
	}
	
	public void expand() {
		// If it is already expanded then return
		if(isExpanded()) {
			return;
		}
		
		// First expand the children
		if(children != null) {
			for(AggregateView child: children) {
				child.expand();
			}
		}
		
		// Expand the native query if any
		if(nativeQuery != null) {
			nativeQuery.expand(this);
		}
		
		// Find and substitute the view references
		attributeList = getExpandedList(getAttributeList());
	}
	
	public List<String> getExpandedList(List<String> input) {
		// Find and substitute the view references
		List<String> newList = new ArrayList<String>();
		for(String attribute: input) {
			if(getViewReference(attribute) != null) {
				newList.addAll(expand(attribute));
			} else {
				newList.add(attribute);
			}
		}
		
		return newList;
	}
	
	private List<String> expand(String attribute) {
		if(attribute.matches(VIEW_REFERENCE_MULTIPLE_REGEX)) {
			throw new IllegalStateException("Cannot refer to more than one view in an attribute: " + attribute);
		}
		String viewName = getViewReference(attribute);
		AggregateView view = getDAS().getView(viewName);

		if(!view.isExpanded()) {
			view.expand();
		}
		
		String prefix = attribute.substring(0, attribute.indexOf(VIEW_REFERENCE_START));
		List<String> expandedAttributes = new ArrayList<String>();
		for(String suffix: view.attributeList) {
			expandedAttributes.add(prefix + suffix);
		}
		
		return expandedAttributes;
	}
	
	@XmlTransient
	public Map<String, StateGraph<State, Edge<State>>> getStateGraph() {
		return this.stateGraph;
	}
	
	public void addStateGraph(EntityType type, StateGraph<State, Edge<State>> value) {

		stateGraph.put(getEntityName(type), value);
	}

	private String getEntityName(EntityType type) {
		if(type.isDomainType()) {
			return DOMAIN + type.getName();
		} else {
			return type.getName();
		}
	}

	/**
	 * Cache the generated state graph by EntityType.
	 * Note: We need to make a distinction between Domain and Reference entity types otherwise
	 * we could end up thrashing between building the graph for these two types.
	 *
	 * @param entityType for which the corresponding StateGraph needs to be built
	 * @return StateGraph instance for the given type for this view
	 */
	public StateGraph<State, Edge<State>> getStateGraph(EntityType entityType) {

		String entityName = getEntityName(entityType);

		if(!stateGraph.containsKey(entityName) ) {
			stateGraph.put(entityName, DFAtoRE.build(this, entityType));
		}
		
		return stateGraph.get(entityName);
	}

	@Override
	public int compareTo(AggregateView o) {
		return (name.equals(o.getName())) ? (version - o.getVersion()) : name.compareTo(o.getName());
	}
}
