/**
 * XOR, empowering Model Driven Architecture in J2EE applications
 *
 * Copyright (c) 2012, Dilip Dalton
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations 
 * under the License.
 */

package tools.xor.view;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.regex.MatchResult;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

import tools.xor.AbstractType;
import tools.xor.AggregateAction;
import tools.xor.EntityType;
import tools.xor.Settings;
import tools.xor.Type;
import tools.xor.service.Shape;
import tools.xor.util.DFAtoRE;
import tools.xor.util.Edge;
import tools.xor.util.InterQuery;
import tools.xor.util.State;
import tools.xor.util.Vertex;
import tools.xor.util.graph.StateTree;
import tools.xor.util.graph.StateGraph;
import tools.xor.util.graph.TypeGraph;
import tools.xor.view.QueryTree.QueryKey;

/**
 * If the view and its children have types then the children will be considered as being subtypes
 *
 * Else, if the children do not have types, it will be considered as query partitions
 * For query partitions, the user can specify child branches if necessary directly.
 * NOTE: If one or more child branch are specified, then only the child branches are executed.
 */

@XmlRootElement(name="AggregateView")
public class AggregateView implements Comparable<AggregateView>, Vertex, View {
	private static final Logger logger = LogManager.getLogger(new Exception().getStackTrace()[0].getClassName());
	
	public static final String  VIEW_REFERENCE_START = "[";
	public static final String  VIEW_REFERENCE_NAME_REGEX = "^.*\\[\\s*(\\w+)\\s*\\].*";
	public static final String  VIEW_REFERENCE_MULTIPLE_REGEX = "^(.*)(\\[\\s*(\\w+)\\s*\\]).*(\\[\\s*\\w+\\s*\\].*)";
	public static final String  REGEX_STRING = "[\\*\\?\\+\\[\\{\\|\\(\\)\\^\\$]";
	public static final Pattern REGEX_STRING_MATCHER = Pattern.compile(REGEX_STRING);

	public static final String DOMAIN = "DOMAIN:";
	public static final String EXACT = "EXACT:";
	public static final String REGEX = "_REGEX_";

	protected String            name;
	protected List<String>      attributeList;

	protected String            typeName; // represents the root entity type
	
	// Each function should be independent of one another
	protected List<Function> function;
	
	// OQL query generated by the system. May not be an optimized version.
	protected OQLQuery          systemOQLQuery;
	
	// OQL query crafted by the user, useful for providing an optimized OQL version.
	protected OQLQuery          userOQLQuery;
	
	// It should refer to the full attribute name
	// SQL - the column names should be PROP1, PROP2 etc...
	protected NativeQuery       nativeQuery;
	
	protected List<StoredProcedure>   storedProcedure;

	// Child AggregateViews are considered as inline views and do not persist independently
	// Their name represents the anchor (the edge) where they connect to. It is a full path
	// starting from the root.
	// View references are named views whose anchor is the path where they appear.
	// If the view to which it attaches does not have a type then it is a container view
	// and all its members are aliases
 	protected List<AggregateView> children;

	protected List<Join>        join;
	
	protected int               version; // The version from which this view is effective
	
	@XmlTransient
	private boolean expanded;

	@XmlTransient
	private Set<String> exactAttributes; // These do not have the recursive operand (*)
	                                     // and exact match can be performed

	@XmlTransient
	private Map<String, Pattern> regexAttributes;

	@XmlTransient
	private Shape shape; // The Shape with which this view is associated
	
	@XmlTransient
	private final Map<QueryKey, QueryTree>  queryCache = new ConcurrentHashMap<>();

	// A view can be valid for multiple entity types, especially if the view refers
	// to the attributes in a base class. Then in this case, the view can be 
	// used by all the subtypes of that base class.
	@XmlTransient
	private final Map<String, StateGraph<State, Edge<State>>> stateGraph =  new ConcurrentHashMap<>();

	public AggregateView(QueryPiece queryPiece) {
		initQuery(queryPiece);
	}
	
	public AggregateView(Type type, String viewName) {
		this(viewName);
		this.typeName = type.getInstanceClass().getName();
	}	
	
	public AggregateView(String viewName) {
		setName(viewName);
	}		

	/**
	 * No-args constructor required for Unmarshalling purpose and also internally by the framework. 
	 * Don't use this directly.
	 */
	public AggregateView() {
	}
	
	private void initQuery(QueryPiece queryPiece) {
		this.name = queryPiece.getName();
		this.typeName = queryPiece.getAggregateType().getInstanceClass().getName();
		
		// We create the OQLQuery object and populate it with information from the query view
		// such as ColumnMeta information
		// The query builder should have populated the OQLQuery object
	}

	@Override
	public boolean isExpanded() {
		return expanded;
	}

	public void setExpanded(boolean expanded) {
		this.expanded = expanded;
	}

	@Override
	public int getVersion() {
		return version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Override
	public List<Join> getJoin() {
		return join;
	}

	public void setJoin(List<Join> join) {
		this.join = join;
	}

	public List<AggregateView> getChildren() {
		return children;
	}

	public void setChildren(List<AggregateView> children) {
		this.children = children;
	}

	@Override
	public List<Function> getFunction () {
		return function;
	}

	public void setFunction (List<Function> functions) {
		this.function = functions;
	}	

	public OQLQuery getSystemOQLQuery() {
		return systemOQLQuery;
	}

	public void setSystemOQLQuery(OQLQuery systemOQLQuery) {
		this.systemOQLQuery = systemOQLQuery;
	}

	@Override
	public OQLQuery getUserOQLQuery() {
		return userOQLQuery;
	}

	@Override
	public void setUserOQLQuery(OQLQuery userOQLQuery) {
		this.userOQLQuery = userOQLQuery;
	}

	@Override
	public NativeQuery getNativeQuery() {
		return nativeQuery;
	}

	public void setNativeQuery(NativeQuery nativeQuery) {
		this.nativeQuery = nativeQuery;
	}

	@Override
	public StoredProcedure getStoredProcedure(final AggregateAction action) {
		StoredProcedure result = null;

		if(getStoredProcedure() != null) {
			for (StoredProcedure sp : getStoredProcedure()) {
				if (sp.getAction() == action) {
					result = sp.copy();
					break;
				}
			}
		}

		return result;
	}

	@Override
	public List<StoredProcedure> getStoredProcedure() {
		return storedProcedure;
	}

	@Override
	public void setStoredProcedure(List<StoredProcedure> storedProcedure) {
		this.storedProcedure = storedProcedure;
	}

	@XmlTransient
	@Override
	public Shape getShape() {
		return this.shape;
	}

	@Override
	public void setShape(Shape shape) {
		this.shape = shape;

		if(children != null) {
			for(View child: children) {
				child.setShape(shape);
			}
		}
	}

	@Override
	public List<String> getAttributes() {
		List<String> result = new LinkedList<>();

		if(getAttributeList() != null) {
			result.addAll(getAttributeList());
		}
		if(getChildren() != null) {
			for (View child : getChildren()) {
				result.addAll(child.getAttributes());
			}
		}

		return result;
	}

	@Override
	public List<String> getAttributeList() {
		return attributeList;
	}

	@Override
	public void setAttributeList(List<String> attributeList) {
		this.attributeList = attributeList;
	}

	@Override public String getTypeName() {
		return typeName;
	}

	@Override
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Override
	public String getName() {
		return name;
	}

	@Override
	public void setName(String name) {
		this.name = name;
	}

	private QueryTree getQueryView(QueryKey viewKey) {
		if(queryCache.containsKey(viewKey)) {
			return queryCache.get(viewKey);
		}

		// Build the QueryTree
		QueryTree<QueryPiece, InterQuery<QueryPiece>> queryTree = new QueryTree(this);
		new FragmentBuilder(queryTree).build((EntityType)viewKey.type);
		queryCache.put(viewKey, queryTree);

		return queryTree;
	}

	@Override
	public QueryTree getQueryTree (Type type, boolean narrow) {
		return getQueryView(new QueryKey(type, name, narrow));
	}

	public static boolean isBuiltInView(String viewName) {
		for(ViewType viewType: ViewType.values()) {
			if(viewName.endsWith(viewType.toString())) {
				return true;
			}
		}

		return false;
	}

	@Override
	public Class inferDomainClass() {
		String suffix = null;
		Class result = null;

		for(ViewType viewType: ViewType.values()) {
			if(name.endsWith(viewType.toString())) {
				suffix = Settings.URI_PATH_DELIMITER + viewType.toString();
				break;
			}
		}

		if(suffix != null) {
			String encodedName = name.substring(0, name.indexOf(suffix));
			String className = Settings.decodeParam(encodedName);
			try {
				result = Class.forName(className);
			}
			catch (ClassNotFoundException e) {
				result = null;
			}
		}

		return result;
	}

	@Override
	public AggregateView copy() {
		AggregateView result = new AggregateView();

		result.setName(name);
		result.setTypeName(typeName);
		if(attributeList != null) {
			result.setAttributeList(new ArrayList<>(attributeList));
		}

		if(function != null) {
			List<Function> functionCopy = new ArrayList<>();
			for(Function f: function) {
				functionCopy.add(new Function(f));
			}
			result.setFunction(functionCopy);
		}

		if(nativeQuery != null) {
			result.setNativeQuery(nativeQuery.copy());
		}

		if(userOQLQuery != null) {
			result.setUserOQLQuery(userOQLQuery.copy());
		}

		if(systemOQLQuery != null) {
			result.setUserOQLQuery(systemOQLQuery.copy());
		}

		if(children != null) {
			List<AggregateView> childrenCopy = new ArrayList<>();
			for(AggregateView c: children) {
				childrenCopy.add(c.copy());
			}
			result.setChildren(childrenCopy);
		}

		result.setJoin(join);

		if(regexAttributes != null) {
			result.regexAttributes = new HashMap(regexAttributes);
		}
		if(exactAttributes != null) {
			result.exactAttributes = new HashSet(exactAttributes);
		}
		
		if(stateGraph != null) {
			for(Map.Entry<String, StateGraph<State, Edge<State>>> entry: stateGraph.entrySet()) {
				result.stateGraph.put(entry.getKey(), entry.getValue().copy());
			}
		}
		
		result.setShape(getShape());

		return result;
	}

	@Override
	public Set<String> getViewReferences() {
		Set<String> result = new HashSet<>();
		
		for(String attribute: getAttributes()) {
			String viewName = getViewReference(attribute);
			if(viewName != null)
				result.add(viewName);
		}
		
		return result;
	}

	public static String getViewReference(String attribute) {
		if(attribute.matches(VIEW_REFERENCE_NAME_REGEX)) {
			Scanner s = new Scanner(attribute);
			try {
				s.findInLine(VIEW_REFERENCE_NAME_REGEX);
				MatchResult result = s.match();
				if(result.groupCount() == 1)
					return result.group(1);
			} finally {
				s.close();
			}
		}

		return null;
	}

	@Override
	public boolean hasViewReference() {

		for (String attribute : getAttributes()) {
			if (getViewReference(attribute) != null)
				return true;
		}
		
		return false;
	}

	@Override
	public void expand() {

		if(getChildren() != null) {
			for(AggregateView child: getChildren()) {
				// EntityType fragments cannot be expanded
				if(child.getTypeName() != null) {
					return;
				}
			}
		}

		// If it is already expanded then return
		if(isExpanded()) {
			return;
		}
		
		// First expand the children
		if(children != null) {
			for(View child: children) {
				child.expand();
			}
		}
		
		// Find and substitute the view references
		attributeList = getExpandedList(getAttributeList());

		// Get the RegEx attributes
		Map<String, Pattern> regexMap = new HashMap<>();
		Set<String> exactSet = new HashSet<>();
		for(String attrPath: this.attributeList) {
			if(DFAtoRE.isRegex(attrPath)) {
				regexMap.put(attrPath, Pattern.compile(attrPath));
			} else {
				exactSet.add(attrPath);
			}
		}
		if(regexMap.size() > 0) {
			this.setRegexAttributes(regexMap);
		}
		if(exactSet.size() > 0) {
			this.setExactAttributes(exactSet);
		}

		setExpanded(true);
	}

	@Override
	public List<String> getExpandedList(List<String> input) {
		// Find and substitute the view references
		List<String> newList = new ArrayList<>();

		if(input != null) {
			for (String attribute : input) {
				if (getViewReference(attribute) != null) {
					newList.addAll(expand(attribute));
				}
				else {
					newList.add(attribute);
				}
			}
		}
		
		return newList;
	}

	@Override
	public Set<String> getFunctionAttributes() {
		Set<String> functionAttributes = new HashSet<>();

		if(getFunction() != null) {
			for (Function function : getFunction()) {
				functionAttributes.addAll(function.getAttributes());
			}
		}

		return functionAttributes;
	}

	private List<String> expand(String attribute) {
		if(attribute.matches(VIEW_REFERENCE_MULTIPLE_REGEX)) {
			throw new IllegalStateException("Cannot refer to more than one view in an attribute: " + attribute);
		}
		String viewName = getViewReference(attribute);
		View view = getShape().getView(viewName);

		// Attributes might be referring to a RegEx expression
		if(view == null) {
			return this.attributeList;
		}

		if(!view.isExpanded()) {
			view.expand();
		}
		
		String prefix = attribute.substring(0, attribute.indexOf(VIEW_REFERENCE_START));
		List<String> expandedAttributes = new ArrayList<>();
		for(String suffix: view.getAttributeList()) {
			expandedAttributes.add(prefix + suffix);
		}
		
		return expandedAttributes;
	}

	@XmlTransient
	@Override
	public Set<String> getExactAttributes ()
	{
		return exactAttributes;
	}

	public void setExactAttributes (Set<String> exactAttributes)
	{
		this.exactAttributes = exactAttributes;
	}

	@XmlTransient
	@Override
	public Map<String, Pattern> getRegexAttributes() {
		return this.regexAttributes;
	}

	public void setRegexAttributes(Map<String, Pattern> regexAttributes) {
		this.regexAttributes = regexAttributes;
	}

	@Override
	public boolean matches(String path) {
		if(regexAttributes != null) {
			for(Pattern p: regexAttributes.values()) {
				Matcher matcher = p.matcher(path);
				if(matcher.matches() || matcher.hitEnd()) {
					return true;
				}
			}
		}

		return false;
	}
	
	@XmlTransient
	public Map<String, StateGraph<State, Edge<State>>> getStateGraph() {
		return this.stateGraph;
	}

	private String getEntityName(EntityType type, boolean isExact) {
		String exactPrefix = isExact ? EXACT : "";

		if(type.isDomainType()) {
			return exactPrefix + DOMAIN + type.getName();
		} else {
			return exactPrefix + type.getName();
		}
	}

	@Override
	public void addTypeGraph (EntityType type, TypeGraph<State, Edge<State>> value, boolean isExact) {

		stateGraph.put(getEntityName(type, isExact), (StateGraph<State, Edge<State>>)value);
	}

	@Override
	public TypeGraph<State, Edge<State>> getTypeGraph (EntityType entityType) {
		return getTypeGraph(entityType, false);
	}

	public TypeGraph<State, Edge<State>> getTypeGraph () {
		if(typeName == null) {
			throw new IllegalStateException("The type for the view needs to be provided");
		}

		// Return the type graph related to the view EntityType
		return getTypeGraph(null);
	}

	@Override
	public TypeGraph<State, Edge<State>> getTypeGraph (EntityType entityType, boolean isExact) {

		String entityName = this.typeName != null ? this.typeName : getEntityName(entityType, isExact);

		// This is not a default view, then we need to construct the type graph for this view
		if(!stateGraph.containsKey(entityName) ) {
			if(typeName != null) {
				Type type = shape.getType(typeName);
				
				// If EntityType is not provided, then use type as the EntityType
				if(entityType == null && type instanceof EntityType) {
					entityType = (EntityType) type;
				}
				if(entityType == null) {
					throw new RuntimeException("The given type should be an entityType: " + typeName);
				}
				if (!type.getInstanceClass().isAssignableFrom(entityType.getInstanceClass())) {
					throw new RuntimeException(
						"The view type " + type.getName()
							+ " should either be the same or a supertype of the given type: "
							+ entityType.getName());
				}
			}
			if(isEdgeGraph(this)) {
				stateGraph.put(entityName, StateTree.build(this, entityType));
			} else {
				stateGraph.put(entityName, DFAtoRE.build(this, entityType));
			}
		}
		
		return stateGraph.get(entityName);
	}

	public static boolean isEdgeGraph(View view) {
		return !view.isExpanded() && view.getTypeName() != null;
	}

	@Override
	public int compareTo(AggregateView o) {
		return (name.equals(o.getName())) ? (version - o.getVersion()) : name.compareTo(o.getName());
	}

	public boolean isMigrateView(Type type) {
		String migrateViewName = AbstractType.getMigrateViewName(type);
		return migrateViewName != null && migrateViewName.equals(getName());
	}

	@Override
	public boolean isValid() {
		TypeGraph typeGraph = getTypeGraph();

		for(String path: attributeList) {
			if(!typeGraph.hasPath(path)) {
				logger.info("Invalid path: " + path);
				return false;
			}
		}
		return true;
	}

	@Override
	public boolean hasUserQuery() {
		return getNativeQuery() != null || getUserOQLQuery() != null || getStoredProcedure(AggregateAction.READ) != null;
	}
}
