DROP PROCEDURE GetPersonBasic IF EXISTS/;

CREATE PROCEDURE GetPersonBasic()
READS SQL DATA
DYNAMIC RESULT SETS 1
BEGIN ATOMIC
  DECLARE result1 CURSOR FOR
  SELECT UUID, 
		 NAME,
		 DISPLAYNAME,
		 DESCRIPTION,
		 ICONURL,
		 DETAILEDDESCRIPTION
	FROM Person;
    
  OPEN result1;
END/;
