CREATE OR REPLACE PROCEDURE GetPersonBasic ( p_ResultSet OUT sys_refcursor )
AS
BEGIN
    OPEN p_ResultSet FOR
        SELECT UUID,NAME,DISPLAYNAME,DESCRIPTION,ICONURL,DETAILEDDESCRIPTION FROM PERSON;

END/;
