CREATE TABLE "OREXPRESSIONTAB" ("ROOTID" NVARCHAR(25) NOT NULL ,
	 "MYID" NVARCHAR(25) NOT NULL ,
	 "LVID" NVARCHAR(25),
	 "EXO_EXPRESSIONS" NVARCHAR(25) NOT NULL ,
	 "EXO_OPERATION" INTEGER NOT NULL ,
	 "EXO_DEFAULTINGSETBITS" DECIMAL(20,
	0),
	 CONSTRAINT "P_5WLAL6_1F1S7" PRIMARY KEY ("MYID")) 
;
CREATE INDEX "I_5WLAL6_142KZ99" ON "OREXPRESSIONTAB" ( "ROOTID" ASC );
