-- PRIVATEORGGROUPTAB

CREATE TABLE "PRIVATEORGGROUPTAB" ("ROOTID" NVARCHAR(25) NOT NULL ,
	 "PGR_PARENT" NVARCHAR(25),
	 "PGR_CATEGORY" NVARCHAR(765),
	 "PGR_CONTEXT" NVARCHAR(765),
	 CONSTRAINT "P_5DSAPJ_142KZ99" PRIMARY KEY ("ROOTID"))  ;

-- US_GROUPTAB

CREATE TABLE "US_GROUPTAB" ("ROOTID" NVARCHAR(25) NOT NULL ,
	 "GR_USERS" NVARCHAR(25),
	 "GR_ISGLOBAL" TINYINT NOT NULL ,
	 "GR_UNIQUENAME" NVARCHAR(765) NOT NULL ,
	 "GR_CREATED" TIMESTAMP NOT NULL ,
	 "GR_MODIFIED" TIMESTAMP NOT NULL ,
	 "GR_PARTITIONNUMBER" INTEGER NOT NULL ,
	 "GR_PURGESTATE" INTEGER NOT NULL,
	 CONSTRAINT "P_1W8Y6GN_142KZ99" PRIMARY KEY ("ROOTID"))  
;
CREATE INDEX "I_1W8Y6GN_SW7HQS" ON "US_GROUPTAB" ( "GR_USERS" ASC )
;
CREATE INDEX "I_1W8Y6GN_16TCDCT" ON "US_GROUPTAB" ( "GR_MODIFIED" ASC )
;
CREATE INDEX "I_1W8Y6GN_6RMCVK" ON "US_GROUPTAB" ( "GR_UNIQUENAME" ASC )
;



-- US_USERTAB

CREATE TABLE "US_USERTAB" ("ROOTID" NVARCHAR(25) NOT NULL ,
	 "CUS_PASSWORDADAPTER" NVARCHAR(150) NOT NULL ,
	 "CUS_ORGANIZATION" NVARCHAR(25) NOT NULL ,
	 "CUS_ISTERMINATED" TINYINT NOT NULL ,
	 "CUS_UNIQUENAME" NVARCHAR(765) NOT NULL ,
	 "CUS_CREATED" TIMESTAMP NOT NULL ,
	 "CUS_MODIFIED" TIMESTAMP NOT NULL ,
	 "CUS_PARTITIONNUMBER" INTEGER NOT NULL ,
	 "CUS_PURGESTATE" INTEGER NOT NULL ,
	 CONSTRAINT "P_1PD3TWP_142KZ99" PRIMARY KEY ("ROOTID"))  
;
CREATE INDEX "I_1PD3TWP_1ENW8PZ" ON "US_USERTAB" ( "CUS_MODIFIED" ASC )
;
CREATE UNIQUE INDEX "I_1PD3TWP_7ELEBN" ON "US_USERTAB" ( "CUS_PARTITIONNUMBER" ASC,
	 "CUS_PASSWORDADAPTER" ASC,
	 "CUS_UNIQUENAME" ASC )
;
CREATE INDEX "I_1PD3TWP_U89FGX" ON "US_USERTAB" ( "CUS_ORGANIZATION" ASC )
;

-- USERTAB

CREATE TABLE "USERTAB" ("ROOTID" NVARCHAR(25) NOT NULL ,
	 "US_USER" NVARCHAR(25) NOT NULL ,
         "US_RESPONSIBLE" NVARCHAR(25),
	 "US_PARTITIONNUMBER" INTEGER NOT NULL ,
	 "US_PURGESTATE" INTEGER NOT NULL ,
	 CONSTRAINT "P_9FVPVU_142KZ99" PRIMARY KEY ("ROOTID"))  
;
CREATE INDEX "I_9FVPVU_9U89N0" ON "USERTAB" ( "US_USER" ASC )
;
CREATE UNIQUE INDEX "I_9FVPVU_G73L1G" ON "USERTAB" ( "US_PARTITIONNUMBER" ASC,
	 "US_USER" ASC );


-- GROUPRESPONSIBLETAB

CREATE TABLE "GROUPRESPONSIBLETAB" ("ROOTID" NVARCHAR(25) NOT NULL ,
	 "MYID" NVARCHAR(25) NOT NULL ,
	 "LVID" NVARCHAR(25),
	 "GRB_GROUP" NVARCHAR(25),
	 "GRB_PROCUREMENTUNIT" NVARCHAR(25),
	 "GRB_DEFAULTINGSETBITS" DECIMAL(20,
	0),
	 CONSTRAINT "P_M6EQRI_1F1S7" PRIMARY KEY ("MYID"))  
;
CREATE INDEX "I_M6EQRI_142KZ99" ON "GROUPRESPONSIBLETAB" ( "ROOTID" ASC )
;
CREATE INDEX "I_M6EQRI_1CGCN9Z" ON "GROUPRESPONSIBLETAB" ( "GRB_GROUP" ASC )
;
CREATE INDEX "I_M6EQRI_H7ELQK" ON "GROUPRESPONSIBLETAB" ( "GRB_PROCUREMENTUNIT" ASC );


-- PROCUREMENTUNITTAB

CREATE TABLE "PROCUREMENTUNITTAB" ("ROOTID" NVARCHAR(25) NOT NULL ,
	 "PROR_UNIQUENAME" NVARCHAR(150) NOT NULL ,
	 "PROR_HIERARCHYPATH" NVARCHAR(1530),
	 "PROR_PARTITIONNUMBER" INTEGER NOT NULL ,
	 "PROR_PURGESTATE" INTEGER NOT NULL ,
	 CONSTRAINT "P_1O77MXT_142KZ99" PRIMARY KEY ("ROOTID"))  
;
CREATE UNIQUE INDEX "I_1O77MXT_1F7IDDH" ON "PROCUREMENTUNITTAB" ( "PROR_PARTITIONNUMBER" ASC,
	 "PROR_UNIQUENAME" ASC )
;
CREATE UNIQUE INDEX "I_1O77MXT_DEHP6P" ON "PROCUREMENTUNITTAB" ( "PROR_PARTITIONNUMBER" ASC,
	 "PROR_HIERARCHYPATH" ASC );


-- US_BASEIDTAB

CREATE TABLE "US_BASEIDTAB" ("ROOTID" NVARCHAR(25) NOT NULL ,
	 "LVID" NVARCHAR(25),
	 "LVINDEX" INTEGER,
	 "VAL" NVARCHAR(25),
	 "PARTITIONNUMBER" INTEGER)  
;
CREATE INDEX "I_1EFB1M0_142KZ99" ON "US_BASEIDTAB" ( "ROOTID" ASC )
;
CREATE INDEX "I_1EFB1M0_1ECKL" ON "US_BASEIDTAB" ( "LVID" ASC )
;
CREATE INDEX "I_1EFB1M0_1TDT" ON "US_BASEIDTAB" ( "VAL" ASC )
;
CREATE UNIQUE INDEX "I_1EFB1M0_1D5B81J" ON "US_BASEIDTAB" ( "ROOTID" ASC,
	 "LVID" ASC,
	 "LVINDEX" ASC,
	 "VAL" ASC );

